blank_issues_enabled: false
contact_links:
- name: "Gimkit Technical Community Discord"
  url: "https://discord.gg/vBHcG76KGQ"
  about: "Ask questions and get help related to Gimloader and other Gimkit-related projects."