name: "Gimloader Bug Report"
description: "Create a report for a bug with Gimloader, not any plugins."
title: "[Gimloader Bug]"
labels: ["bug", "gimloader"]
body:
- type: "checkboxes"
  attributes:
    label: "I have made sure of the following:"
    options:
      - label: "I have updated Gimloader to the latest version"
        required: true
      - label: "This problem is not caused by a plugin"
        required: true
- type: "textarea"
  attributes:
    label: "Describe the bug"
  validations:
    required: true
- type: "textarea"
  attributes:
    label: "Steps to reproduce (if possible)"