name: "Gimloader Feature Request"
description: "Suggest a feature to be added to Gimloader."
title: "[Gimloader Request]"
labels: ["enhancement", "gimloader"]
body:
- type: "textarea"
  attributes:
    label: "Describe the feature you would like to see added"
  validations:
    required: true