name: "Plugin Request"
description: "Suggest a plugin to potentially be made."
title: "[Plugin Request]"
labels: ["enhancement", "plugin"]
body:
- type: "textarea"
  attributes:
    label: "Describe the plugin you would like to see added"
  validations:
    required: true