name: Publish @gimloader/build package
on:
  push:
    branches:
      - main
    paths:
      - 'packages/build/**'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    defaults:
      run:
        working-directory: ./packages/build
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun i --frozen-lockfile
      - run: bun run build
      - run: bun publish --access public